### PR TITLE
filters/keys_filter: ignore bad URLs 

### LINKED ISSUE #69: send_notice raises URI::InvalidURIError with invalid URIs
If a user visits a badly formed URI (say, http://example.com/foo]bar), and the app raises an exception (perhaps because of the badly formed URI), the airbrake gem will raise a second exception while trying to parse `notice[:context][:url]`, which prevents the original error from reaching Airbrake.   Here's a partial stack from such an error:

```
/Users/jon/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/uri/common.rb, line 747
/Users/jon/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/uri/common.rb, line 1232
airbrake-ruby (1.1.0) lib/airbrake-ruby/filters/keys_filter.rb, line 32
airbrake-ruby (1.1.0) lib/airbrake-ruby/filter_chain.rb, line 64
airbrake-ruby (1.1.0) lib/airbrake-ruby/filter_chain.rb, line 62
airbrake-ruby (1.1.0) lib/airbrake-ruby/notifier.rb, line 123
airbrake-ruby (1.1.0) lib/airbrake-ruby/notifier.rb, line 45
airbrake-ruby (1.1.0) lib/airbrake-ruby.rb, line 282
airbrake-ruby (1.1.0) lib/airbrake-ruby.rb, line 136
airbrake (5.1.0) lib/airbrake/rack/middleware.rb, line 39
```

Perhaps `KeysFilter#call` should catch URI::InvalidURIError and quietly return?   Or replace `notice[:context][:url]` with `"<invalid URI>"` ?

### PR DESCRIPTION
**Pull request by kyrylo**
Fixes #69 (send_notice raises URI::InvalidURIError with invalid URIs)

We lose the ability to filter query params, but the good thing is that
we can deliver unmodified URL.

### CODE REVIEW

**Comment by vmihailenco** [comment]
Why not to to catch URI::InvalidURIError exception and don't filter URL params?

**Comment by kyrylo** [comment]
This is another option, yes. Why is it better, though?

**Comment by vmihailenco** [comment]
It is better because it is the first thing that comes on mind when code throws an exception.

**Comment by kyrylo** [comment]
Amended the PR to use this approach instead.

PTAL

File: lib/airbrake-ruby/filters/keys_filter.rb [hunk 1]
```diff
@@ -74,6 +72,23 @@ def filter_url_params(url)
...
+
+        if url.respond_to?(:query) && url.query
+          notice[:context][:url] = filter_url_params(url)
+        end
+      end
+
+      ##
+      # Tries to convert a String to a URI, but if fails, returns the original
+      # String unchanged.
+      def parse_url(url_string)
```
Comment (vmihailenco) [inline lib/airbrake-ruby/filters/keys_filter.rb]: What is the point of the method that returns URI or string?

File: lib/airbrake-ruby/filters/keys_filter.rb [hunk 2]
```diff
@@ -74,6 +72,23 @@ def filter_url_params(url)
 
         url.to_s
       end
+
+      def filter_url(notice)
```
Comment (vmihailenco) [inline lib/airbrake-ruby/filters/keys_filter.rb]: try
  url = URI(url_string)
rescue URI::InvalidURIError
  return
notice[:context][:url] = filter_url_params(url)

**Comment by kyrylo** [comment]
Applied suggested changes and added one more test. 

PTAL

**Comment by vmihailenco** [comment]
LGTM
