### PR TITLE
backtrace: special case classloader path

### LINKED ISSUE #139: Found parsing error in my logs
```
E, [2016-12-13T20:33:16.736000 #29171] ERROR -- : can't parse 'uri_3a_classloader_3a_.gems.faye_minus_websocket_minus_0_dot_10_dot_5.lib.faye.websocket.api.invokeOther13:dispatch_event(uri_3a_classloader_3a_/gems/faye_minus_websocket_minus_0_dot_10_dot_5/lib/faye/websocket/uri:classloader:/gems/faye-websocket-0.10.5/lib/faye/websocket/api.rb:109)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
```

Using JRuby 9.1.6.0 and version 1.6.0 of this gem.

Full trace:

```
364631234 [main] ERROR bay_event_forwarder.rb  - org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition.
Backtrace:
        org.apache.kafka.clients.producer.internals.FutureRecordMetadata.valueOrError(org/apache/kafka/clients/producer/internals/FutureRecordMetadata.java:65)
        org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(org/apache/kafka/clients/producer/internals/FutureRecordMetadata.java:60)
        org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(org/apache/kafka/clients/producer/internals/FutureRecordMetadata.java:25)
        java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
        org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:468)
        org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:326)
        uri_3a_classloader_3a_.lib.sources.bay_event_forwarder.invokeOther13:get(uri_3a_classloader_3a_/lib/sources/uri:classloader:/lib/sources/bay_event_forwarder.rb:85)
        uri_3a_classloader_3a_.lib.sources.bay_event_forwarder.produce!(uri:classloader:/lib/sources/bay_event_forwarder.rb:85)
        uri_3a_classloader_3a_.lib.sources.bay_event_forwarder.invokeOther0:produce!(uri_3a_classloader_3a_/lib/sources/uri:classloader:/lib/sources/bay_event_forwarder.rb:192)
        uri_3a_classloader_3a_.lib.sources.bay_event_forwarder.block in setup_everything!(uri:classloader:/lib/sources/bay_event_forwarder.rb:192)
        org.jruby.RubyProc.call(org/jruby/RubyProc.java:324)
        org.jruby.RubyProc.call19(org/jruby/RubyProc.java:308)
        org.jruby.RubyProc$INVOKER$i$0$0$call19.call(org/jruby/RubyProc$INVOKER$i$0$0$call19.gen)
        uri_3a_classloader_3a_.lib.sdp.park_server.events.invokeOther46:call(uri_3a_classloader_3a_/lib/sdp/park_server/uri:classloader:/lib/sdp/park_server/events.rb:160)
        uri_3a_classloader_3a_.lib.sdp.park_server.events.process_faye_event_containing_park_server_event(uri:classloader:/lib/sdp/park_server/events.rb:160)
        uri_3a_classloader_3a_.lib.sdp.park_server.events.invokeOther16:process_faye_event_containing_park_server_event(uri_3a_classloader_3a_/lib/sdp/park_server/uri:classloader:/lib/sdp/park_server/events.rb:190)
        uri_3a_classloader_3a_.lib.sdp.park_server.events.handle_faye_event(uri:classloader:/lib/sdp/park_server/events.rb:190)
        uri_3a_classloader_3a_.lib.sdp.park_server.events.invokeOther23:handle_faye_event(uri_3a_classloader_3a_/lib/sdp/park_server/uri:classloader:/lib/sdp/park_server/events.rb:293)
        uri_3a_classloader_3a_.lib.sdp.park_server.events.block in consume(uri:classloader:/lib/sdp/park_server/events.rb:293)
        org.jruby.RubyProc.call(org/jruby/RubyProc.java:324)
        org.jruby.RubyProc.call19(org/jruby/RubyProc.java:308)
        org.jruby.RubyProc$INVOKER$i$0$0$call19.call(org/jruby/RubyProc$INVOKER$i$0$0$call19.gen)
        uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.event_emitter.invokeOther0:call(uri_3a_classloader_3a_/gems/websocket_minus_driver_minus_0_dot_6_dot_4_minus_java/lib/websocket/driver/uri:classloader:/gems/websocket-driver-0
.6.4-java/lib/websocket/driver/event_emitter.rb:39)
        uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.event_emitter.block in emit(uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/event_emitter.rb:39)
        org.jruby.RubyArray.each(org/jruby/RubyArray.java:1734)
        org.jruby.RubyArray$INVOKER$i$0$0$each.call(org/jruby/RubyArray$INVOKER$i$0$0$each.gen)
        uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.event_emitter.invokeOther6:each(uri_3a_classloader_3a_/gems/websocket_minus_driver_minus_0_dot_6_dot_4_minus_java/lib/websocket/driver/uri:classloader:/gems/websocket-driver-0
.6.4-java/lib/websocket/driver/event_emitter.rb:38)
        uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.event_emitter.emit(uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/event_emitter.rb:38)
        uri_3a_classloader_3a_.gems.faye_minus_websocket_minus_0_dot_10_dot_5.lib.faye.websocket.api.event_target.invokeOther33:emit(uri_3a_classloader_3a_/gems/faye_minus_websocket_minus_0_dot_10_dot_5/lib/faye/websocket/api/uri:classloader:/gems/faye-websocket-0.10.5/lib/faye/websock
et/api/event_target.rb:44)
        uri_3a_classloader_3a_.gems.faye_minus_websocket_minus_0_dot_10_dot_5.lib.faye.websocket.api.event_target.dispatch_event(uri:classloader:/gems/faye-websocket-0.10.5/lib/faye/websocket/api/event_target.rb:44)
        uri_3a_classloader_3a_.gems.faye_minus_websocket_minus_0_dot_10_dot_5.lib.faye.websocket.api.invokeOther13:dispatch_event(uri_3a_classloader_3a_/gems/faye_minus_websocket_minus_0_dot_10_dot_5/lib/faye/websocket/uri:classloader:/gems/faye-websocket-0.10.5/lib/faye/websocket/api.
rb:109)
        uri_3a_classloader_3a_.gems.faye_minus_websocket_minus_0_dot_10_dot_5.lib.faye.websocket.api.receive_message(uri:classloader:/gems/faye-websocket-0.10.5/lib/faye/websocket/api.rb:109)
        uri_3a_classloader_3a_.gems.faye_minus_websocket_minus_0_dot_10_dot_5.lib.faye.websocket.api.invokeOther6:receive_message(uri_3a_classloader_3a_/gems/faye_minus_websocket_minus_0_dot_10_dot_5/lib/faye/websocket/uri:classloader:/gems/faye-websocket-0.10.5/lib/faye/websocket/api.
rb:43)
        uri_3a_classloader_3a_.gems.faye_minus_websocket_minus_0_dot_10_dot_5.lib.faye.websocket.api.block in initialize(uri:classloader:/gems/faye-websocket-0.10.5/lib/faye/websocket/api.rb:43)
        org.jruby.RubyProc.call(org/jruby/RubyProc.java:324)
        org.jruby.RubyProc.call19(org/jruby/RubyProc.java:308)
        org.jruby.RubyProc$INVOKER$i$0$0$call19.call(org/jruby/RubyProc$INVOKER$i$0$0$call19.gen)
        uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.event_emitter.invokeOther0:call(uri_3a_classloader_3a_/gems/websocket_minus_driver_minus_0_dot_6_dot_4_minus_java/lib/websocket/driver/uri:classloader:/gems/websocket-driver-0
.6.4-java/lib/websocket/driver/event_emitter.rb:39)
        uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.event_emitter.block in emit(uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/event_emitter.rb:39)
        org.jruby.RubyArray.each(org/jruby/RubyArray.java:1734)
        org.jruby.RubyArray$INVOKER$i$0$0$each.call(org/jruby/RubyArray$INVOKER$i$0$0$each.gen)
        uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.event_emitter.invokeOther6:each(uri_3a_classloader_3a_/gems/websocket_minus_driver_minus_0_dot_6_dot_4_minus_java/lib/websocket/driver/uri:classloader:/gems/websocket-driver-0
.6.4-java/lib/websocket/driver/event_emitter.rb:38)
        uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.event_emitter.emit(uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/event_emitter.rb:38)
        uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.hybi.invokeOther38:emit(uri_3a_classloader_3a_/gems/websocket_minus_driver_minus_0_dot_6_dot_4_minus_java/lib/websocket/driver/uri:classloader:/gems/websocket-driver-0.6.4-jav
a/lib/websocket/driver/hybi.rb:396)
        uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.hybi.emit_message(uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/hybi.rb:396)
        uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.hybi.invokeOther102:emit_message(uri_3a_classloader_3a_/gems/websocket_minus_driver_minus_0_dot_6_dot_4_minus_java/lib/websocket/driver/uri:classloader:/gems/websocket-driver-
0.6.4-java/lib/websocket/driver/hybi.rb:379)
        uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.hybi.emit_frame(uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/hybi.rb:379)
        uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.hybi.invokeOther18:emit_frame(uri_3a_classloader_3a_/gems/websocket_minus_driver_minus_0_dot_6_dot_4_minus_java/lib/websocket/driver/uri:classloader:/gems/websocket-driver-0.6
.4-java/lib/websocket/driver/hybi.rb:123)
        uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.hybi.parse(uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/hybi.rb:123)
        uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.client.invokeSuper24:parse(uri_3a_classloader_3a_/gems/websocket_minus_driver_minus_0_dot_6_dot_4_minus_java/lib/websocket/driver/uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/client.rb:63)
        uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.client.parse(uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/client.rb:63)
        uri_3a_classloader_3a_.gems.faye_minus_websocket_minus_0_dot_10_dot_5.lib.faye.websocket.api.invokeOther5:parse(uri_3a_classloader_3a_/gems/faye_minus_websocket_minus_0_dot_10_dot_5/lib/faye/websocket/uri:classloader:/gems/faye-websocket-0.10.5/lib/faye/websocket/api.rb:148)
        uri_3a_classloader_3a_.gems.faye_minus_websocket_minus_0_dot_10_dot_5.lib.faye.websocket.api.parse(uri:classloader:/gems/faye-websocket-0.10.5/lib/faye/websocket/api.rb:148)
        org.jruby.RubyClass.finvoke(org/jruby/RubyClass.java:531)

        org.jruby.RubyBasicObject.send19(org/jruby/RubyBasicObject.java:1668)
        org.jruby.RubyBasicObject$INVOKER$i$send19.call(org/jruby/RubyBasicObject$INVOKER$i$send19.gen)
        uri_3a_classloader_3a_.gems.faye_minus_websocket_minus_0_dot_10_dot_5.lib.faye.websocket.client.invokeOther5:__send__(uri_3a_classloader_3a_/gems/faye_minus_websocket_minus_0_dot_10_dot_5/lib/faye/websocket/uri:classloader:/gems/faye-websocket-0.10.5/lib/faye/websocket/client.rb:80)
        uri_3a_classloader_3a_.gems.faye_minus_websocket_minus_0_dot_10_dot_5.lib.faye.websocket.client.receive_data(uri:classloader:/gems/faye-websocket-0.10.5/lib/faye/websocket/client.rb:80)
        uri_3a_classloader_3a_.gems.eventmachine_minus_1_dot_2_dot_1_minus_java.lib.eventmachine.invokeOther155:receive_data(uri_3a_classloader_3a_/gems/eventmachine_minus_1_dot_2_dot_1_minus_java/lib/uri:classloader:/gems/eventmachine-1.2.1-java/lib/eventmachine.rb:1537)
        uri_3a_classloader_3a_.gems.eventmachine_minus_1_dot_2_dot_1_minus_java.lib.eventmachine.event_callback(uri:classloader:/gems/eventmachine-1.2.1-java/lib/eventmachine.rb:1537)
        uri_3a_classloader_3a_.gems.eventmachine_minus_1_dot_2_dot_1_minus_java.lib.jeventmachine.invokeOther5:event_callback(uri_3a_classloader_3a_/gems/eventmachine_minus_1_dot_2_dot_1_minus_java/lib/uri:classloader:/gems/eventmachine-1.2.1-java/lib/jeventmachine.rb:94)
        uri_3a_classloader_3a_.gems.eventmachine_minus_1_dot_2_dot_1_minus_java.lib.jeventmachine.eventCallback(uri:classloader:/gems/eventmachine-1.2.1-java/lib/jeventmachine.rb:94)
        org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHandler.invokeRuby(org/jruby/javasupport/proxy/JavaProxyConstructor.java:255)
        org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHandler.invoke(org/jruby/javasupport/proxy/JavaProxyConstructor.java:238)
        org.jruby.proxy.com.rubyeventmachine.EmReactor$Proxy1.eventCallback(org/jruby/proxy/com/rubyeventmachine/EmReactor$Proxy1)
        com.rubyeventmachine.EmReactor.eventCallback(com/rubyeventmachine/EmReactor.java:89)
        org.jruby.proxy.com.rubyeventmachine.EmReactor$Proxy1.__super$eventCallback(org/jruby/proxy/com/rubyeventmachine/EmReactor$Proxy1)
        java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
        org.jruby.javasupport.JavaMethod.invokeDirectSuperWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:408)
        org.jruby.javasupport.JavaMethod.tryProxyInvocation(org/jruby/javasupport/JavaMethod.java:611)
        org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:287)
        org.jruby.RubyClass.finvoke(org/jruby/RubyClass.java:522)
        org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHandler.invokeRuby(org/jruby/javasupport/proxy/JavaProxyConstructor.java:260)
        org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHandler.invoke(org/jruby/javasupport/proxy/JavaProxyConstructor.java:238)
        org.jruby.proxy.com.rubyeventmachine.EmReactor$Proxy1.eventCallback(org/jruby/proxy/com/rubyeventmachine/EmReactor$Proxy1)
        com.rubyeventmachine.EmReactor.isReadable(com/rubyeventmachine/EmReactor.java:259)
        com.rubyeventmachine.EmReactor.processIO(com/rubyeventmachine/EmReactor.java:204)
        com.rubyeventmachine.EmReactor.run(com/rubyeventmachine/EmReactor.java:111)
        java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
        org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:438)
        org.jruby.javasupport.JavaMethod.tryProxyInvocation(org/jruby/javasupport/JavaMethod.java:623)
        org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:299)
        RUBY.run_machine(uri:classloader:/gems/eventmachine-1.2.1-java/lib/jeventmachine.rb:113)
        RUBY.run(uri:classloader:/gems/eventmachine-1.2.1-java/lib/eventmachine.rb:194)
        bin.sources.bay_event_forwarder.invokeOther35:run(bin/sources/bay_event_forwarder.rb:28)
        bin.sources.bay_event_forwarder.start!(bin/sources/bay_event_forwarder.rb:28)
        bin.sources.bay_event_forwarder.invokeOther49:start!(bin/sources/bay_event_forwarder.rb:51)
        bin.sources.bay_event_forwarder.<main>(bin/sources/bay_event_forwarder.rb:51)
        java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:627)
        org.jruby.Ruby.runScript(org/jruby/Ruby.java:846)
        org.jruby.Ruby.runNormally(org/jruby/Ruby.java:761)
        org.jruby.Ruby.runNormally(org/jruby/Ruby.java:779)
        org.jruby.Ruby.runFromMain(org/jruby/Ruby.java:592)
        org.jruby.Main.doRunFromMain(org/jruby/Main.java:425)
        org.jruby.Main.internalRun(org/jruby/Main.java:313)
        org.jruby.Main.run(org/jruby/Main.java:242)
        org.jruby.mains.JRubyMain.run(org/jruby/mains/JRubyMain.java:108)
        org.jruby.mains.JRubyMain.main(org/jruby/mains/JRubyMain.java:39)
        org.jruby.mains.JarMain.main(org/jruby/mains/JarMain.java:6)
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition.
        at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.valueOrError(org/apache/kafka/clients/producer/internals/FutureRecordMetadata.java:65)
        at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(org/apache/kafka/clients/producer/internals/FutureRecordMetadata.java:60)
        at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(org/apache/kafka/clients/producer/internals/FutureRecordMetadata.java:25)
        at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:468)
        at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:326)
        at uri_3a_classloader_3a_.lib.sources.bay_event_forwarder.invokeOther13:get(uri_3a_classloader_3a_/lib/sources/uri:classloader:/lib/sources/bay_event_forwarder.rb:85)
        at uri_3a_classloader_3a_.lib.sources.bay_event_forwarder.produce!(uri:classloader:/lib/sources/bay_event_forwarder.rb:85)
        at uri_3a_classloader_3a_.lib.sources.bay_event_forwarder.invokeOther0:produce!(uri_3a_classloader_3a_/lib/sources/uri:classloader:/lib/sources/bay_event_forwarder.rb:192)
        at uri_3a_classloader_3a_.lib.sources.bay_event_forwarder.block in setup_everything!(uri:classloader:/lib/sources/bay_event_forwarder.rb:192)
        at org.jruby.RubyProc.call(org/jruby/RubyProc.java:324)
        at org.jruby.RubyProc.call19(org/jruby/RubyProc.java:308)
        at org.jruby.RubyProc$INVOKER$i$0$0$call19.call(org/jruby/RubyProc$INVOKER$i$0$0$call19.gen)
        at uri_3a_classloader_3a_.lib.sdp.park_server.events.invokeOther46:call(uri_3a_classloader_3a_/lib/sdp/park_server/uri:classloader:/lib/sdp/park_server/events.rb:160)
        at uri_3a_classloader_3a_.lib.sdp.park_server.events.process_faye_event_containing_park_server_event(uri:classloader:/lib/sdp/park_server/events.rb:160)
        at uri_3a_classloader_3a_.lib.sdp.park_server.events.invokeOther16:process_faye_event_containing_park_server_event(uri_3a_classloader_3a_/lib/sdp/park_server/uri:classloader:/lib/sdp/park_server/events.rb:190)
        at uri_3a_classloader_3a_.lib.sdp.park_server.events.handle_faye_event(uri:classloader:/lib/sdp/park_server/events.rb:190)
        at uri_3a_classloader_3a_.lib.sdp.park_server.events.invokeOther23:handle_faye_event(uri_3a_classloader_3a_/lib/sdp/park_server/uri:classloader:/lib/sdp/park_server/events.rb:293)
        at uri_3a_classloader_3a_.lib.sdp.park_server.events.block in consume(uri:classloader:/lib/sdp/park_server/events.rb:293)
        at org.jruby.RubyProc.call(org/jruby/RubyProc.java:324)

        at org.jruby.RubyProc.call19(org/jruby/RubyProc.java:308)
        at org.jruby.RubyProc$INVOKER$i$0$0$call19.call(org/jruby/RubyProc$INVOKER$i$0$0$call19.gen)
        at uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.event_emitter.invokeOther0:call(uri_3a_classloader_3a_/gems/websocket_minus_driver_minus_0_dot_6_dot_4_minus_java/lib/websocket/driver/uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/event_emitter.rb:39)
        at uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.event_emitter.block in emit(uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/event_emitter.rb:39)
        at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1734)
        at org.jruby.RubyArray$INVOKER$i$0$0$each.call(org/jruby/RubyArray$INVOKER$i$0$0$each.gen)
        at uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.event_emitter.invokeOther6:each(uri_3a_classloader_3a_/gems/websocket_minus_driver_minus_0_dot_6_dot_4_minus_java/lib/websocket/driver/uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/event_emitter.rb:38)
        at uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.event_emitter.emit(uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/event_emitter.rb:38)
        at uri_3a_classloader_3a_.gems.faye_minus_websocket_minus_0_dot_10_dot_5.lib.faye.websocket.api.event_target.invokeOther33:emit(uri_3a_classloader_3a_/gems/faye_minus_websocket_minus_0_dot_10_dot_5/lib/faye/websocket/api/uri:classloader:/gems/faye-websocket-0.10.5/lib/faye/websocket/api/event_target.rb:44)
        at uri_3a_classloader_3a_.gems.faye_minus_websocket_minus_0_dot_10_dot_5.lib.faye.websocket.api.event_target.dispatch_event(uri:classloader:/gems/faye-websocket-0.10.5/lib/faye/websocket/api/event_target.rb:44)
        at uri_3a_classloader_3a_.gems.faye_minus_websocket_minus_0_dot_10_dot_5.lib.faye.websocket.api.invokeOther13:dispatch_event(uri_3a_classloader_3a_/gems/faye_minus_websocket_minus_0_dot_10_dot_5/lib/faye/websocket/uri:classloader:/gems/faye-websocket-0.10.5/lib/faye/websocket/api.rb:109)
        at uri_3a_classloader_3a_.gems.faye_minus_websocket_minus_0_dot_10_dot_5.lib.faye.websocket.api.receive_message(uri:classloader:/gems/faye-websocket-0.10.5/lib/faye/websocket/api.rb:109)
        at uri_3a_classloader_3a_.gems.faye_minus_websocket_minus_0_dot_10_dot_5.lib.faye.websocket.api.invokeOther6:receive_message(uri_3a_classloader_3a_/gems/faye_minus_websocket_minus_0_dot_10_dot_5/lib/faye/websocket/uri:classloader:/gems/faye-websocket-0.10.5/lib/faye/websocket/api.rb:43)
        at uri_3a_classloader_3a_.gems.faye_minus_websocket_minus_0_dot_10_dot_5.lib.faye.websocket.api.block in initialize(uri:classloader:/gems/faye-websocket-0.10.5/lib/faye/websocket/api.rb:43)
        at org.jruby.RubyProc.call(org/jruby/RubyProc.java:324)
        at org.jruby.RubyProc.call19(org/jruby/RubyProc.java:308)
        at org.jruby.RubyProc$INVOKER$i$0$0$call19.call(org/jruby/RubyProc$INVOKER$i$0$0$call19.gen)
        at uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.event_emitter.invokeOther0:call(uri_3a_classloader_3a_/gems/websocket_minus_driver_minus_0_dot_6_dot_4_minus_java/lib/websocket/driver/uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/event_emitter.rb:39)
        at uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.event_emitter.block in emit(uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/event_emitter.rb:39)
        at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1734)
        at org.jruby.RubyArray$INVOKER$i$0$0$each.call(org/jruby/RubyArray$INVOKER$i$0$0$each.gen)
        at uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.event_emitter.invokeOther6:each(uri_3a_classloader_3a_/gems/websocket_minus_driver_minus_0_dot_6_dot_4_minus_java/lib/websocket/driver/uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/event_emitter.rb:38)
        at uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.event_emitter.emit(uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/event_emitter.rb:38)
        at uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.hybi.invokeOther38:emit(uri_3a_classloader_3a_/gems/websocket_minus_driver_minus_0_dot_6_dot_4_minus_java/lib/websocket/driver/uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/hybi.rb:396)
        at uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.hybi.emit_message(uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/hybi.rb:396)
        at uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.hybi.invokeOther102:emit_message(uri_3a_classloader_3a_/gems/websocket_minus_driver_minus_0_dot_6_dot_4_minus_java/lib/websocket/driver/uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/hybi.rb:379)
        at uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.hybi.emit_frame(uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/hybi.rb:379)
        at uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.hybi.invokeOther18:emit_frame(uri_3a_classloader_3a_/gems/websocket_minus_driver_minus_0_dot_6_dot_4_minus_java/lib/websocket/driver/uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/hybi.rb:123)
        at uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.hybi.parse(uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/hybi.rb:123)
        at uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.client.invokeSuper24:parse(uri_3a_classloader_3a_/gems/websocket_minus_driver_minus_0_dot_6_dot_4_minus_java/lib/websocket/driver/uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/client.rb:63)
        at uri_3a_classloader_3a_.gems.websocket_minus_driver_minus_0_dot_6_dot_4_minus_java.lib.websocket.driver.client.parse(uri:classloader:/gems/websocket-driver-0.6.4-java/lib/websocket/driver/client.rb:63)
        at uri_3a_classloader_3a_.gems.faye_minus_websocket_minus_0_dot_10_dot_5.lib.faye.websocket.api.invokeOther5:parse(uri_3a_classloader_3a_/gems/faye_minus_websocket_minus_0_dot_10_dot_5/lib/faye/websocket/uri:classloader:/gems/faye-websocket-0.10.5/lib/faye/websocket/api.rb:148)
        at uri_3a_classloader_3a_.gems.faye_minus_websocket_minus_0_dot_10_dot_5.lib.faye.websocket.api.parse(uri:classloader:/gems/faye-websocket-0.10.5/lib/faye/websocket/api.rb:148)
        at org.jruby.RubyClass.finvoke(org/jruby/RubyClass.java:531)
        at org.jruby.RubyBasicObject.send19(org/jruby/RubyBasicObject.java:1668)
        at org.jruby.RubyBasicObject$INVOKER$i$send19.call(org/jruby/RubyBasicObject$INVOKER$i$send19.gen)
        at uri_3a_classloader_3a_.gems.faye_minus_websocket_minus_0_dot_10_dot_5.lib.faye.websocket.client.invokeOther5:__send__(uri_3a_classloader_3a_/gems/faye_minus_websocket_minus_0_dot_10_dot_5/lib/faye/websocket/uri:classloader:/gems/faye-websocket-0.10.5/lib/faye/websocket/client.rb:80)
        at uri_3a_classloader_3a_.gems.faye_minus_websocket_minus_0_dot_10_dot_5.lib.faye.websocket.client.receive_data(uri:classloader:/gems/faye-websocket-0.10.5/lib/faye/websocket/client.rb:80)
        at uri_3a_classloader_3a_.gems.eventmachine_minus_1_dot_2_dot_1_minus_java.lib.eventmachine.invokeOther155:receive_data(uri_3a_classloader_3a_/gems/eventmachine_minus_1_dot_2_dot_1_minus_java/lib/uri:classloader:/gems/eventmachine-1.2.1-java/lib/eventmachine.rb:1537)
        at uri_3a_classloader_3a_.gems.eventmachine_minus_1_dot_2_dot_1_minus_java.lib.eventmachine.event_callback(uri:classloader:/gems/eventmachine-1.2.1-java/lib/eventmachine.rb:1537)
        at uri_3a_classloader_3a_.gems.eventmachine_minus_1_dot_2_dot_1_minus_java.lib.jeventmachine.invokeOther5:event_callback(uri_3a_classloader_3a_/gems/eventmachine_minus_1_dot_2_dot_1_minus_java/lib/uri:classloader:/gems/eventmachine-1.2.1-java/lib/jeventmachine.rb:94)
        at uri_3a_classloader_3a_.gems.eventmachine_minus_1_dot_2_dot_1_minus_java.lib.jeventmachine.eventCallback(uri:classloader:/gems/eventmachine-1.2.1-java/lib/jeventmachine.rb:94)
        at org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHandler.invokeRuby(org/jruby/javasupport/proxy/JavaProxyConstructor.java:255)
        at org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHandler.invoke(org/jruby/javasupport/proxy/JavaProxyConstructor.java:238)
        at org.jruby.proxy.com.rubyeventmachine.EmReactor$Proxy1.eventCallback(org/jruby/proxy/com/rubyeventmachine/EmReactor$Proxy1)
        at com.rubyeventmachine.EmReactor.eventCallback(com/rubyeventmachine/EmReactor.java:89)
        at org.jruby.proxy.com.rubyeventmachine.EmReactor$Proxy1.__super$eventCallback(org/jruby/proxy/com/rubyeventmachine/EmReactor$Proxy1)
        at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
        at org.jruby.javasupport.JavaMethod.invokeDirectSuperWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:408)
        at org.jruby.javasupport.JavaMethod.tryProxyInvocation(org/jruby/javasupport/JavaMethod.java:611)
        at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:287)
        at org.jruby.RubyClass.finvoke(org/jruby/RubyClass.java:522)
        at org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHandler.invokeRuby(org/jruby/javasupport/proxy/JavaProxyConstructor.java:260)
        at org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHandler.invoke(org/jruby/javasupport/proxy/JavaProxyConstructor.java:238)
        at org.jruby.proxy.com.rubyeventmachine.EmReactor$Proxy1.eventCallback(org/jruby/proxy/com/rubyeventmachine/EmReactor$Proxy1)
        at com.rubyeventmachine.EmReactor.isReadable(com/rubyeventmachine/EmReactor.java:259)
        at com.rubyeventmachine.EmReactor.processIO(com/rubyeventmachine/EmReactor.java:204)
        at com.rubyeventmachine.EmReactor.run(com/rubyeventmachine/EmReactor.java:111)
        at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)

       at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
        at org.jruby.javasupport.JavaMethod.invokeDirectSuperWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:408)
        at org.jruby.javasupport.JavaMethod.tryProxyInvocation(org/jruby/javasupport/JavaMethod.java:611)
        at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:287)
        at org.jruby.RubyClass.finvoke(org/jruby/RubyClass.java:522)
        at org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHandler.invokeRuby(org/jruby/javasupport/proxy/JavaProxyConstructor.java:260)
        at org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHandler.invoke(org/jruby/javasupport/proxy/JavaProxyConstructor.java:238)
        at org.jruby.proxy.com.rubyeventmachine.EmReactor$Proxy1.eventCallback(org/jruby/proxy/com/rubyeventmachine/EmReactor$Proxy1)
        at com.rubyeventmachine.EmReactor.isReadable(com/rubyeventmachine/EmReactor.java:259)
        at com.rubyeventmachine.EmReactor.processIO(com/rubyeventmachine/EmReactor.java:204)
        at com.rubyeventmachine.EmReactor.run(com/rubyeventmachine/EmReactor.java:111)
        at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:438)
        at org.jruby.javasupport.JavaMethod.tryProxyInvocation(org/jruby/javasupport/JavaMethod.java:623)
        at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:299)
        at RUBY.run_machine(uri:classloader:/gems/eventmachine-1.2.1-java/lib/jeventmachine.rb:113)
        at RUBY.run(uri:classloader:/gems/eventmachine-1.2.1-java/lib/eventmachine.rb:194)
        at bin.sources.bay_event_forwarder.invokeOther35:run(bin/sources/bay_event_forwarder.rb:28)
        at bin.sources.bay_event_forwarder.start!(bin/sources/bay_event_forwarder.rb:28)
        at bin.sources.bay_event_forwarder.invokeOther49:start!(bin/sources/bay_event_forwarder.rb:51)
        at bin.sources.bay_event_forwarder.<main>(bin/sources/bay_event_forwarder.rb:51)
        at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:627)
        at org.jruby.Ruby.runScript(org/jruby/Ruby.java:846)
        at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:761)
        at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:779)
        at org.jruby.Ruby.runFromMain(org/jruby/Ruby.java:592)
        at org.jruby.Main.doRunFromMain(org/jruby/Main.java:425)
        at org.jruby.Main.internalRun(org/jruby/Main.java:313)
        at org.jruby.Main.run(org/jruby/Main.java:242)
        at org.jruby.mains.JRubyMain.run(org/jruby/mains/JRubyMain.java:108)
        at org.jruby.mains.JRubyMain.main(org/jruby/mains/JRubyMain.java:39)
        at org.jruby.mains.JarMain.main(org/jruby/mains/JarMain.java:6)
```

### PR DESCRIPTION
**Pull request by kyrylo**
Fixes #139 (Found parsing error in my logs)

### CODE REVIEW

File: spec/backtrace_spec.rb [hunk 1]
```diff
@@ -80,14 +80,19 @@
...
+        ]
         # rubocop:enable Metrics/LineLength
       end
 
       let(:parsed_backtrace) do
         # rubocop:disable Metrics/LineLength
         [{ file: 'uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/protocol.rb', line: 158, function: 'uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.net.protocol.rbuf_fill' },
-         { file: 'bin/processors/image_uploader.rb', line: 21, function: 'bin.processors.image_uploader.block in make_streams' }]
+         { file: 'bin/processors/image_uploader.rb', line: 21, function: 'bin.processors.image_uploader.block in make_streams' },
+         { file: 'uri_3a_classloader_3a_/gems/faye_minus_websocket_minus_0_dot_10_dot_5/lib/faye/websocket/uri:classloader:/gems/faye-websocket-0.10.5/lib/faye/websocket/api.rb', line: 109, function: 'uri_3a_classloader_3a_.gems.faye_minus_websocket_minus_0_dot_10_dot_5.lib.faye.websocket.api.invokeOther13:dispatch_event' },
```
Comment (vmihailenco) [inline spec/backtrace_spec.rb]: Looks like this should be

```
file: /gems/faye-websocket-0.10.5/lib/faye/websocket/api.rb
function: dispatch_event
```

?

Comment (kyrylo) [inline spec/backtrace_spec.rb]: I don't really know whether the Java classloader stuff is useful, so I guess safe to leave as is. Are you sure it's gibberish?

Comment (vmihailenco) [inline spec/backtrace_spec.rb]: I am sure that user wants what I posted. If Java classloader stuff is not useful then it is not clear why we are parsing it at all.

Comment (kyrylo) [inline spec/backtrace_spec.rb]: Cool, I'll change it. We are parsing it because I don't want to leave out potentially useful information.

Comment (vmihailenco) [inline spec/backtrace_spec.rb]: Okay, I dont insist and we can revisit when JRuby users show up.

>https://github.com/airbrake/airbrake-ruby/blob/master/spec/backtrace_spec.rb#L83

should be "block in make_streams", because "bin.processors.image_uploader" is generated from file

**Comment by vmihailenco** [comment]
LGTM, though build fails

**Comment by kyrylo** [comment]
Fixed build.
