### PR TITLE
config: don't raise when current environment is ignored

### LINKED ISSUE #80: Airbrake: unexpected code (405). Body: Method Not Allowed
This error above was caused by something that took me a while to figure out. I am running airbrake (5.0.5) on my application and found that this error comes up when you are setting the `project_id` and the `project_key` to blank values. 

File: `config/initializers/airbrake.rb`
```ruby
Airbrake.configure do |c|
  c.project_id = ''
  c.project_key = ''
```
```shell
rake airbrake:deploy USERNAME=my_user ENVIRONMENT=staging REVISION=revision REPOSITORY=github_repo VERSION=1
````
results from command

```shell
Request URI: /api/v4/projects/deploys?key=
Req: #<Net::HTTP::Post POST>
Endpoint: #<URI::HTTPS https://airbrake.io/api/v4/projects/deploys?key=>
Notice: {:environment=>"alpha", :username=>"my_user", :revision=>"revision", :repository=>"github_repo", :version=>"1"}
Response: #<Net::HTTPMethodNotAllowed 405 Method Not Allowed readbody=true>
E, [2016-05-11T11:55:50.492599 #97422] ERROR -- : **Airbrake: unexpected code (405). Body: Method Not Allowed
```

## My Understanding of Results

Most of what I was seeing now makes sense. based off what I see above I get why it resulted in the 405. Because the **project_id** is not present it changes the URL. So a 405 is exactly what you expect. when you don't have a **project_id**

```
Request URI: /api/v4/projects/{project_id}/deploys?key={project_key}
Req: #<Net::HTTP::Post POST>
Endpoint: #<URI::HTTPS https://airbrake.io/api/v4/projects/{project_id}/deploys?key=39f22e0d8d5f97df880bd62567b0f2b6>
Notice: {:environment=>"alpha", :username=>"my_user", :revision=>"d2eae2dd353f67f7c95f97b7fcbe23ff170382c6", :repository=>"github_repo", :version=>"1"}
Response: #<Net::HTTPCreated 201 Created readbody=true>
```

### Possible Solution

I think a good idea would be to add a check to make sure that the project_id and project key are present before you send the post. If not present warn the user but perform the action anyway. As you could be in the test environment or in the development environment. However there is much more to take into account as you can run the rake airbrake:deploy using RAILS_ENV=development and ENVIRONMENT=staging. So might be be also a solution to only warn if the ENVIRONMENT that you are deploying to is not in the ignore_environemnts varable. 

`c.ignore_environments = %w(test development)`

```ruby
require 'airbrake/sidekiq/error_handler'

airbrake_yml = Rails.root.join('config', 'airbrake.yml')
if File.exist?(airbrake_yml)
  config = YAML.load_file(airbrake_yml)
  puts '------------------------- Deprecation Warning -------------------------'
  puts(
    'Deprecation Warning: airbrake.yml is being removed please use .env '\
    'with AIRBRAKE_PROJECT_ID & AIRBRAKE_PROJECT_KEY'
  )
  puts '------------------------- Deprecation Warning -------------------------'
  project_key = config[:project_key]
  project_id = config[:project_id]
end

project_key = (ENV['AIRBRAKE_PROJECT_KEY'] || project_key).to_s
project_id = (ENV['AIRBRAKE_PROJECT_ID'] || project_id).to_s
# I found that there is a lot of confusing error messages when keys are blank
# To solve this we are placing a warning to the user so that they can
# address the problem. However the warning does not apply when you are testing
# as there is no use case currently that would require the application to talk
# to airbrake when in test mode
unless Rails.env.test?
  puts 'WARN: Airbrake Project key is blank' if project_key.blank?
  puts 'WARN: Airbrake Project id is blank' if project_id.blank?
end
```

https://github.com/airbrake/airbrake-ruby/blob/master/lib/airbrake-ruby/config.rb#L100
I am think here on the endpoint method might be the best spot to raise the warning as it seams to be the point in which the data is required to work correctly.

### PR DESCRIPTION
**Pull request by kyrylo**
Fixes #80 (Airbrake: unexpected code (405). Body: Method Not Allowed)
and many other complains of people who are confused by the current
behaviour when we raise an error when they ignore current environment.

### CODE REVIEW

File: lib/airbrake-ruby/config.rb [hunk 1]
```diff
@@ -125,6 +125,23 @@ def merge(config_hash)
...
+      return true if ignored_environment?
+      return false unless project_id.is_a?(Integer)
+      project_key.is_a?(String) && !project_key.empty?
+    end
+
+    ##
+    # @return [Boolean] true if the config ignores current environment, false
+    #   otherwise
+    def ignored_environment?
+      return false if ignore_environments.none?
```
Comment (sgray11) [inline lib/airbrake-ruby/config.rb]: This seems like an unnecessary early return. The next line should cover everything, right?

Comment (kyrylo) [inline lib/airbrake-ruby/config.rb]: Correct, good catch, fixed.

**Comment by sgray11** [comment]
LGTM pending CI

**Comment by vmihailenco** [comment]
LGTM

File: lib/airbrake-ruby/notifier.rb [hunk 2]
```diff
@@ -30,7 +30,7 @@ class Notifier
     def initialize(user_config)
       @config = (user_config.is_a?(Config) ? user_config : Config.new(user_config))
 
-      unless [@config.project_id, @config.project_key].all?
```
Comment (mvbehr) [inline lib/airbrake-ruby/notifier.rb]: @kyrylo 
This change got me into a bit of a trouble.
I upgraded from `v1.3.1` to `v1.4.1` and it started to complain about `'both :project_id and :project_key are required'`
But I had these variables set in my `.env` file.

After re-checking the changelog I found out, that I had my `project_id` set to `"test"` in development environment.
And now it needs to be an integer.
Maybe you can change the error message to be more explicit?
`':project_id and :project_key are required as integer'`

Comment (kyrylo) [inline lib/airbrake-ruby/notifier.rb]: Try a newer version (1.4.2). It was fixed by https://github.com/airbrake/airbrake-ruby/pull/89 :)
Sorry for the inconvenience.

Comment (mvbehr) [inline lib/airbrake-ruby/notifier.rb]: No worries! :)
I am referring to the error message itself. 
It tells me, that the two variables are required, when both values were already set.
So I had to look at the code to get to know it has to be an Integer.

Anyway, I am fine with the state right now and also think its just an edge case.
Thanks!
