### PR TITLE
filters/thread_filter: fixed segfault on Ruby 2.1.3

### LINKED ISSUE #229: Another segfault report
* Airbrake version: 6.1.1
* Ruby version: 2.1.3-p242
* Framework name & version: Rails 3.2.21

#### Airbrake config

````ruby
Airbrake.configure do |config|
  config.environment = Rails.env
  config.project_key = [redacted]
  config.project_id = [redacted]
  #config.ignore_environments = %w(development test)  # commented out to run airbrake:test
  config.root_directory = Rails.root
end
````

#### Description

I'm not sure if this is related to #204 but it _is_ another segfault.  I'm running a Rails 3.2.21 app in Ruby 2.1.3p242 using Airbrake 6.1.1 and Airbrake-Ruby 2.2.5.

It's segfaulting during a `rake airbrake:test` run.  It works fine using Airbrake 5.7.1 and Airbrake-Ruby 1.8.0.

I've attached [airbrake_segfault.txt](https://github.com/airbrake/airbrake-ruby/files/1024086/airbrake_segfault.txt) with the details but here's a little taste …

````
/Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:242: [BUG] Segmentation fault at 0x00000000000000
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin16.0]

-- Control frame information -----------------------------------------------
c:0092 p:---- s:0395 e:000394 CFUNC  :to_s
c:0091 p:0008 s:0392 e:000391 BLOCK  /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:242 [FINISH]
c:0090 p:---- s:0388 e:000387 IFUNC
c:0089 p:---- s:0386 e:000385 CFUNC  :each
c:0088 p:---- s:0384 e:000383 CFUNC  :map
c:0087 p:0162 s:0381 e:000379 METHOD /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:242
c:0086 p:0017 s:0372 e:000371 BLOCK  /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:55
c:0085 p:0034 s:0370 e:000369 METHOD /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:77
c:0084 p:0013 s:0366 e:000365 METHOD /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:54
c:0083 p:0016 s:0361 e:000359 BLOCK  /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:242 [FINISH]
c:0082 p:---- s:0356 e:000355 IFUNC
c:0081 p:---- s:0354 e:000353 CFUNC  :each
c:0080 p:---- s:0352 e:000351 CFUNC  :map
c:0079 p:0162 s:0349 e:000347 METHOD /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:242
c:0078 p:0017 s:0340 e:000339 BLOCK  /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:55
c:0077 p:0034 s:0338 e:000337 METHOD /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:77
c:0076 p:0013 s:0334 e:000333 METHOD /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:54
c:0075 p:0016 s:0329 e:000327 BLOCK  /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:242 [FINISH]
c:0074 p:---- s:0324 e:000323 IFUNC
c:0073 p:---- s:0322 e:000321 CFUNC  :each
c:0072 p:---- s:0320 e:000319 CFUNC  :map
c:0071 p:0162 s:0317 e:000315 METHOD /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:242
c:0070 p:0017 s:0308 e:000307 BLOCK  /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:55
c:0069 p:0034 s:0306 e:000305 METHOD /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:77
c:0068 p:0013 s:0302 e:000301 METHOD /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:54
c:0067 p:0016 s:0297 e:000295 BLOCK  /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:242 [FINISH]
c:0066 p:---- s:0292 e:000291 IFUNC
c:0065 p:---- s:0290 e:000289 CFUNC  :each
c:0064 p:---- s:0288 e:000287 CFUNC  :map
c:0063 p:0162 s:0285 e:000283 METHOD /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:242
c:0062 p:0017 s:0276 e:000275 BLOCK  /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:55
c:0061 p:0034 s:0274 e:000273 METHOD /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:77
c:0060 p:0013 s:0270 e:000269 METHOD /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:54
c:0059 p:0016 s:0265 e:000263 BLOCK  /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:242 [FINISH]
c:0058 p:---- s:0260 e:000259 IFUNC
c:0057 p:---- s:0258 e:000257 CFUNC  :each
c:0056 p:---- s:0256 e:000255 CFUNC  :map
c:0055 p:0162 s:0253 e:000251 METHOD /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:242
c:0054 p:0017 s:0244 e:000243 BLOCK  /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:47
c:0053 p:0034 s:0241 e:000240 METHOD /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:77
c:0052 p:0013 s:0237 e:000236 METHOD /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:46
c:0051 p:0024 s:0232 e:000231 METHOD /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/json/encoding.rb:31
c:0050 p:0021 s:0227 e:000226 METHOD /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/core_ext/object/to_json.rb:
c:0049 p:0011 s:0223 e:000222 BLOCK  /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/airbrake-ruby-2.2.5/lib/airbrake-ruby/notice.rb:92 [FINISH]
c:0048 p:---- s:0219 e:000218 CFUNC  :loop
c:0047 p:0007 s:0216 e:000215 METHOD /Users/matte/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/airbrake-ruby-2.2.5/lib/airbrake-ruby/notice.rb:90
````

Any help is appreciated.  I'm using the 5.7.1/1.8.0 pairing for now.  Thanks in advance.

(e)

### PR DESCRIPTION
**Pull request by kyrylo**
Fixes #229 (Another segfault report)

Ruby segfaults whenever it tries to access `:__recursive_key__`.
Unfortunately, there's no other good way to avoid this segfault.
`:__recursive_key__` is set by PrettyPrint, so it's very common.

### CODE REVIEW

File: lib/airbrake-ruby/filters/thread_filter.rb [hunk 1]
```diff
@@ -57,6 +64,7 @@ def thread_variables(th)
 
       def fiber_variables(th)
         th.keys.map.with_object({}) do |key, h|
+          next if IGNORED_FIBER_VARIABLES.any? { |v| v == key }
```
Comment (vmihailenco) [inline lib/airbrake-ruby/filters/thread_filter.rb]: Can we ignore all vars that starts with `_`? I wanted to suggest this before, but did not want to complicate without a good reason.

Comment (kyrylo) [inline lib/airbrake-ruby/filters/thread_filter.rb]: Sounds good.
