### PR TITLE
backtrace: improve generic stackframe regexp

### LINKED ISSUE #24: Airbrake::Error - can't parse '/Users/grammakov/repositories/weintervene/config.ru:in `new''
Moved from: https://github.com/airbrake/airbrake/issues/467#issuecomment-169760796.

### PR DESCRIPTION
**Pull request by kyrylo**
Fixes #24 (Airbrake::Error - can't parse '/Users/grammakov/repositories
/weintervene/config.ru:in `new'')

### CODE REVIEW

File: spec/backtrace_spec.rb [hunk 1]
```diff
@@ -75,26 +75,46 @@
...
-         {:file=>"/home/bingo/.gem/ruby/2.2.2/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb", :line=>349, :function=>"block in visit_mixin"}]
-        # rubocop:enable Metrics/LineLength, Style/HashSyntax, Style/SpaceInsideHashLiteralBraces, Style/SpaceAroundOperators
-      end
+        let(:ex) { AirbrakeTestError.new.tap { |e| e.set_backtrace(generic_bt) } }
 
-      it "returns a properly formatted array of hashes" do
-        expect(described_class.parse(ex)).to eq(parsed_backtrace)
+        let(:parsed_backtrace) do
+          [{ file: '/Users/grammakov/repositories/weintervene/config.ru',
+             line: nil,
```
Comment (vmihailenco) [inline spec/backtrace_spec.rb]: Backend handles null as 0.

**Comment by vmihailenco** [comment]
LGTM

File: spec/backtrace_spec.rb (hunk 1 above)
Comment (kyrylo) [inline spec/backtrace_spec.rb]: Thanks for the info. I guess this is correct behaviour for this library, nevertheless :)
