### PR TITLE
filter_chain: don't try to filter nil files

### LINKED ISSUE #117: undefined method `sub!' for nil:NilClass
* Airbrake version: 1.4.6
* Ruby version: JRuby 9.1.5.0
* Framework name & version: N/A

#### Airbrake config

Only project id, project key, and `environment`.

#### Description

I’ve got this exception + back trace being written out to my log file:

```
org.jruby.exceptions.RaiseException: (ReadTimeout) Net::ReadTimeout
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.net.protocol.rbuf_fill(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/protocol.rb:158)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.net.protocol.read(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/protocol.rb:104)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.net.http.response.block in read_body_0(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http/response.rb:290)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.net.http.response.inflater(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http/response.rb:275)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.net.http.response.read_body_0(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http/response.rb:280)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.net.http.response.read_body(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http/response.rb:201)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.net.http.response.body(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http/response.rb:226)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.net.http.response.reading_body(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http/response.rb:163)
	at uri_3a_classloader_3a_.gems.aws_minus_sdk_minus_core_minus_2_dot_5_dot_6.lib.seahorse.client.net_http.patches.new_transport_request(uri:classloader:/gems/aws-sdk-core-2.5.6/lib/seahorse/client/net_http/patches.rb:37)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.net.http.request(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:1397)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.net.http.block in request(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:1390)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.net.http.start(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:857)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.net.http.request(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:1388)
	at uri_3a_classloader_3a_.gems.httparty_minus_0_dot_14_dot_0.lib.httparty.request.perform(uri:classloader:/gems/httparty-0.14.0/lib/httparty/request.rb:118)
	at uri_3a_classloader_3a_.gems.httparty_minus_0_dot_14_dot_0.lib.httparty.perform_request(uri:classloader:/gems/httparty-0.14.0/lib/httparty.rb:560)
	at uri_3a_classloader_3a_.gems.httparty_minus_0_dot_14_dot_0.lib.httparty.get(uri:classloader:/gems/httparty-0.14.0/lib/httparty.rb:486)
	at uri_3a_classloader_3a_.gems.park_server_minus_1_dot_5_dot_1.lib.park_server.client.perform(uri:classloader:/gems/park_server-1.5.1/lib/park_server/client.rb:110)
	at uri_3a_classloader_3a_.gems.park_server_minus_1_dot_5_dot_1.lib.park_server.client.get(uri:classloader:/gems/park_server-1.5.1/lib/park_server/client.rb:55)
	at uri_3a_classloader_3a_.lib.processors.image_upload.fetch_image(uri:classloader:/lib/processors/image_upload.rb:93)
	at uri_3a_classloader_3a_.lib.processors.image_upload.process!(uri:classloader:/lib/processors/image_upload.rb:157)
	at bin.processors.image_uploader.block in make_streams(bin/processors/image_uploader.rb:21)
```

And I’m passing that exception to `Airbrake.notify_sync` and it’s raising an exception with this message:

```
undefined method `sub!' for nil:NilClass
```

just FYI, I also have a megaton of “can’t parse” error messages in my logs, as I reported in #116 — so I might be getting some of the info in the logs mixed up. (I _really_ need to switch to structured logging.)

### PR DESCRIPTION
**Pull request by kyrylo**
Fixes #117 (undefined method `sub!' for nil:NilClass)

The problem can be reproduced when airbrake-ruby tries to send an
exception with a backtrace, which couldn't be parsed. In that case we
put the whole frame into `function`, leaving `line` and `file` nil.

### CODE REVIEW

File: lib/airbrake-ruby/filter_chain.rb [hunk 1]
```diff
@@ -13,7 +13,8 @@ class FilterChain
       notice[:errors].each do |error|
         Gem.path.each do |gem_path|
           error[:backtrace].each do |frame|
-            frame[:file].sub!(/\A#{gem_path}/, '[GEM_ROOT]'.freeze)
+            next unless (file = frame[:file])
```
Comment (vmihailenco) [inline lib/airbrake-ruby/filter_chain.rb]: Would be nice to have a comment here repeating what you said in PR description "when airbrake-ruby tries to send an exception with a backtrace, which couldn't be parsed. In that case we put the whole frame into function, leaving line and file nil."

File: lib/airbrake-ruby/filter_chain.rb [hunk 2]
```diff
@@ -67,7 +68,8 @@ def root_directory_filter(root_directory)
       proc do |notice|
         notice[:errors].each do |error|
           error[:backtrace].each do |frame|
-            frame[:file].sub!(/\A#{root_directory}/, '[PROJECT_ROOT]'.freeze)
+            next unless (file = frame[:file])
+            file.sub!(/\A#{root_directory}/, '[PROJECT_ROOT]'.freeze)
           end
```
Comment (vmihailenco) [inline lib/airbrake-ruby/filter_chain.rb]: Also you probably should combine those 2 filters together to save some CPU time.

**Comment by vmihailenco** [comment]
LGTM

File: lib/airbrake-ruby/filter_chain.rb (hunk 1 above)
Comment (kyrylo) [inline lib/airbrake-ruby/filter_chain.rb]: Added.

File: lib/airbrake-ruby/filter_chain.rb (hunk 2 above)
Comment (kyrylo) [inline lib/airbrake-ruby/filter_chain.rb]: I don't think it would be possible to do that without creating messy code. This particular filter executes only if the `root_direction` option is defined. This proc doesn't know about the config and I wouldn't want to pass it just for 1 check. They look similar only on the surface.
