### PR TITLE
Send thread information by default

### LINKED ISSUE #187: Save context of a current thread
Lets assume we have a complex logic, which has multiple steps, and you can't access previous variables that affects on the current state of logic where an exception happened. Right now it's not possible to find out how it came into current state, except to go through the logger for the same time. Would be nice to save context in a `Thread.current` and use it inside the `Notifier`.

### PR DESCRIPTION
**Pull request by kyrylo**
Fixes #187 (Save context of a current thread)
Replaces #194

Instead of providing an abstraction over `Thread.thread_variable_set`,
simply send everything we know about current thread.

### CODE REVIEW

File: lib/airbrake-ruby/filters/thread_filter.rb [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+        if (vars = thread_variables(th)).any?
+          thread_info[:thread_variables] = vars
+        end
+
+        if (vars = fiber_variables(th)).any?
+          thread_info[:fiber_variables] = vars
+        end
+
+        if (alive = th.alive?)
+          thread_info[:alive?] = alive
```
Comment (vmihailenco) [inline lib/airbrake-ruby/filters/thread_filter.rb]: How current thread can possibly be not alive?

File: lib/airbrake-ruby/filters/thread_filter.rb [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+      def fiber_variables(th)
+        th.keys.map.with_object({}) { |key, h| h[key] = th[key].inspect }
+      end
+
+      def add_thread_info(th, thread_info)
+        thread_info[:self] = th.inspect
+        thread_info[:group] = th.group.list.map(&:inspect)
+        thread_info[:pending_interrupt?] = th.pending_interrupt?
+        thread_info[:priority] = th.priority
+        thread_info[:stop?] = th.stop?
```
Comment (vmihailenco) [inline lib/airbrake-ruby/filters/thread_filter.rb]: why stop is here and alive is not? how current thread can be dead?

File: lib/airbrake-ruby/filters/thread_filter.rb (hunk 1 above)
Comment (kyrylo) [inline lib/airbrake-ruby/filters/thread_filter.rb]: It can't. Removed.

File: lib/airbrake-ruby/filters/thread_filter.rb (hunk 2 above)
Comment (kyrylo) [inline lib/airbrake-ruby/filters/thread_filter.rb]: It can't. Removed.

**Comment by kyrylo** [comment]
PTAL

File: spec/notifier_spec.rb [hunk 3]
```diff
@@ -154,9 +154,16 @@ def expect_a_request_with_headers(headers)
...
+            /"params":{"bingo":\["bango"\],"bongo":"bish".*}/
           )
         end
+
+        # it "features 'params/thread'" do
+        #   expect_a_request_with_body(
+        #     /"params":{.*"thread":.*}/
+        #   )
+
+        # end
```
Comment (vmihailenco) [inline spec/notifier_spec.rb]: overlook?

Comment (kyrylo) [inline spec/notifier_spec.rb]: Yeah, forgot to uncomment. Thanks!

**Comment by kshnurov** [comment]
@vmihailenco @kyrylo how do I disable this filter? Adding one more to remove thread variables is a stupid approach.

**Comment by kyrylo** [comment]
There's no other way at the moment. I created https://github.com/airbrake/airbrake-ruby/issues/290 to talk about this.
