### PR TITLE
backtrace: fix JRuby exceptions support that are non-throwables

### LINKED ISSUE #183: Can’t parse JRuby backtrace
This happened last week so I don’t recall the exact circumstances… I _believe_ I was using the current/latest version but I’m not 100% sure. Sorry so vague.

```
0 [main] ERROR FOO  - Java::OrgPostgresqlUtil::PSQLException: The connection attempt failed.
Backtrace:
	org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(org/postgresql/core/v3/ConnectionFactoryImpl.java:257)
	org.postgresql.core.ConnectionFactory.openConnection(org/postgresql/core/ConnectionFactory.java:65)
	org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(org/postgresql/jdbc2/AbstractJdbc2Connection.java:149)
	org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(org/postgresql/jdbc3/AbstractJdbc3Connection.java:35)
	org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(org/postgresql/jdbc3g/AbstractJdbc3gConnection.java:22)
	org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(org/postgresql/jdbc4/AbstractJdbc4Connection.java:47)
	org.postgresql.jdbc4.Jdbc4Connection.<init>(org/postgresql/jdbc4/Jdbc4Connection.java:30)
	org.postgresql.Driver.makeConnection(org/postgresql/Driver.java:414)
	org.postgresql.Driver.connect(org/postgresql/Driver.java:282)
	java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
	org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:468)
	org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:326)
	RUBY.connect(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/adapters/jdbc.rb:226)
	RUBY.make_new(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool.rb:116)
	RUBY.make_new(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:228)
	RUBY.available(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:201)
	RUBY._acquire(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:137)
	RUBY.block in acquire(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:151)
	RUBY.block in sync(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:282)
	org.jruby.ext.thread.Mutex.synchronize(org/jruby/ext/thread/Mutex.java:148)
	org.jruby.ext.thread.Mutex$INVOKER$i$0$0$synchronize_DBG.call(org/jruby/ext/thread/Mutex$INVOKER$i$0$0$synchronize_DBG.gen)
	RUBY.sync(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:282)
	RUBY.acquire(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:150)
	RUBY.hold(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:106)
	RUBY.synchronize(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/database/connecting.rb:285)
	RUBY.server_version(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/adapters/shared/postgres.rb:508)
	RUBY.server_version(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/adapters/shared/postgres.rb:1793)
	RUBY.select_sql(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/dataset/sql.rb:233)
	RUBY.each(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/dataset/actions.rb:149)
	org.jruby.RubyClass.finvoke(org/jruby/RubyClass.java:512)
	org.jruby.RubyEnumerable.callEach19(org/jruby/RubyEnumerable.java:116)
	org.jruby.RubyEnumerable.collectCommon(org/jruby/RubyEnumerable.java:838)
	org.jruby.RubyEnumerable.map(org/jruby/RubyEnumerable.java:830)
	org.jruby.RubyEnumerable$INVOKER$s$0$0$map_DBG.call(org/jruby/RubyEnumerable$INVOKER$s$0$0$map_DBG.gen)
	RUBY.map(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/dataset/actions.rb:455)
	RUBY.get_checkpoints(/Users/pavi/dev/sdp-streams/lib/sources/bay_event_forwarder.rb:147)
	org.jruby.RubyClass.finvoke(org/jruby/RubyClass.java:522)
	org.jruby.RubyBasicObject.send19(org/jruby/RubyBasicObject.java:1680)
	org.jruby.RubyKernel.send19(org/jruby/RubyKernel.java:1998)
	org.jruby.RubyKernel$INVOKER$s$send19_DBG.call(org/jruby/RubyKernel$INVOKER$s$send19_DBG.gen)
	RUBY.send_to(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/contracts-0.15.0/lib/contracts/method_reference.rb:43)
	RUBY.call_with(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/contracts-0.15.0/lib/contracts/call_with.rb:79)
	RUBY.block in get_checkpoints(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/contracts-0.15.0/lib/contracts/method_handler.rb:138)
	org.jruby.RubyProc.call(org/jruby/RubyProc.java:289)
	RUBY.get_sites_with_checkpoints(/Users/pavi/dev/sdp-streams/lib/sources/bay_event_forwarder.rb:162)
	org.jruby.RubyClass.finvoke(org/jruby/RubyClass.java:522)
	org.jruby.RubyBasicObject.send19(org/jruby/RubyBasicObject.java:1680)
	org.jruby.RubyKernel.send19(org/jruby/RubyKernel.java:1998)
	org.jruby.RubyKernel$INVOKER$s$send19_DBG.call(org/jruby/RubyKernel$INVOKER$s$send19_DBG.gen)
	RUBY.send_to(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/contracts-0.15.0/lib/contracts/method_reference.rb:43)
	RUBY.call_with(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/contracts-0.15.0/lib/contracts/call_with.rb:79)
	RUBY.block in get_sites_with_checkpoints(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/contracts-0.15.0/lib/contracts/method_handler.rb:138)
	org.jruby.RubyProc.call(org/jruby/RubyProc.java:289)
	RUBY.start!(bin/sources/bay_event_forwarder.rb:24)
	RUBY.<main>(bin/sources/bay_event_forwarder.rb:54)
	org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:840)
	org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:844)
	org.jruby.Ruby.runNormally(org/jruby/Ruby.java:747)
	org.jruby.Ruby.runNormally(org/jruby/Ruby.java:760)
	org.jruby.Ruby.runFromMain(org/jruby/Ruby.java:573)
	org.jruby.Main.doRunFromMain(org/jruby/Main.java:417)
	org.jruby.Main.internalRun(org/jruby/Main.java:305)
	org.jruby.Main.run(org/jruby/Main.java:232)
	org.jruby.Main.main(org/jruby/Main.java:204)
E, [2017-03-13T09:53:20.144000 #60300] ERROR -- : can't parse 'org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(org/postgresql/core/v3/ConnectionFactoryImpl.java:257)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.147000 #60300] ERROR -- : can't parse 'org.postgresql.core.ConnectionFactory.openConnection(org/postgresql/core/ConnectionFactory.java:65)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.148000 #60300] ERROR -- : can't parse 'org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(org/postgresql/jdbc2/AbstractJdbc2Connection.java:149)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.148000 #60300] ERROR -- : can't parse 'org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(org/postgresql/jdbc3/AbstractJdbc3Connection.java:35)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.148000 #60300] ERROR -- : can't parse 'org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(org/postgresql/jdbc3g/AbstractJdbc3gConnection.java:22)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.148000 #60300] ERROR -- : can't parse 'org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(org/postgresql/jdbc4/AbstractJdbc4Connection.java:47)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.149000 #60300] ERROR -- : can't parse 'org.postgresql.jdbc4.Jdbc4Connection.<init>(org/postgresql/jdbc4/Jdbc4Connection.java:30)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.149000 #60300] ERROR -- : can't parse 'org.postgresql.Driver.makeConnection(org/postgresql/Driver.java:414)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.149000 #60300] ERROR -- : can't parse 'org.postgresql.Driver.connect(org/postgresql/Driver.java:282)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.149000 #60300] ERROR -- : can't parse 'java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.150000 #60300] ERROR -- : can't parse 'org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:468)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.150000 #60300] ERROR -- : can't parse 'org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:326)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.150000 #60300] ERROR -- : can't parse 'RUBY.connect(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/adapters/jdbc.rb:226)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.150000 #60300] ERROR -- : can't parse 'RUBY.make_new(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool.rb:116)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.151000 #60300] ERROR -- : can't parse 'RUBY.make_new(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:228)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.151000 #60300] ERROR -- : can't parse 'RUBY.available(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:201)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.151000 #60300] ERROR -- : can't parse 'RUBY._acquire(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:137)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.151000 #60300] ERROR -- : can't parse 'RUBY.block in acquire(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:151)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.152000 #60300] ERROR -- : can't parse 'RUBY.block in sync(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:282)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.152000 #60300] ERROR -- : can't parse 'org.jruby.ext.thread.Mutex.synchronize(org/jruby/ext/thread/Mutex.java:148)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.152000 #60300] ERROR -- : can't parse 'org.jruby.ext.thread.Mutex$INVOKER$i$0$0$synchronize_DBG.call(org/jruby/ext/thread/Mutex$INVOKER$i$0$0$synchronize_DBG.gen)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.152000 #60300] ERROR -- : can't parse 'RUBY.sync(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:282)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.153000 #60300] ERROR -- : can't parse 'RUBY.acquire(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:150)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.153000 #60300] ERROR -- : can't parse 'RUBY.hold(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:106)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.153000 #60300] ERROR -- : can't parse 'RUBY.synchronize(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/database/connecting.rb:285)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.153000 #60300] ERROR -- : can't parse 'RUBY.server_version(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/adapters/shared/postgres.rb:508)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.153000 #60300] ERROR -- : can't parse 'RUBY.server_version(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/adapters/shared/postgres.rb:1793)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.154000 #60300] ERROR -- : can't parse 'RUBY.select_sql(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/dataset/sql.rb:233)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.154000 #60300] ERROR -- : can't parse 'RUBY.each(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/dataset/actions.rb:149)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.154000 #60300] ERROR -- : can't parse 'org.jruby.RubyClass.finvoke(org/jruby/RubyClass.java:512)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.154000 #60300] ERROR -- : can't parse 'org.jruby.RubyEnumerable.callEach19(org/jruby/RubyEnumerable.java:116)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.154000 #60300] ERROR -- : can't parse 'org.jruby.RubyEnumerable.collectCommon(org/jruby/RubyEnumerable.java:838)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.155000 #60300] ERROR -- : can't parse 'org.jruby.RubyEnumerable.map(org/jruby/RubyEnumerable.java:830)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.155000 #60300] ERROR -- : can't parse 'org.jruby.RubyEnumerable$INVOKER$s$0$0$map_DBG.call(org/jruby/RubyEnumerable$INVOKER$s$0$0$map_DBG.gen)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.155000 #60300] ERROR -- : can't parse 'RUBY.map(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/dataset/actions.rb:455)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.155000 #60300] ERROR -- : can't parse 'RUBY.get_checkpoints(/Users/pavi/dev/sdp-streams/lib/sources/bay_event_forwarder.rb:147)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.155000 #60300] ERROR -- : can't parse 'org.jruby.RubyClass.finvoke(org/jruby/RubyClass.java:522)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.156000 #60300] ERROR -- : can't parse 'org.jruby.RubyBasicObject.send19(org/jruby/RubyBasicObject.java:1680)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.156000 #60300] ERROR -- : can't parse 'org.jruby.RubyKernel.send19(org/jruby/RubyKernel.java:1998)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.156000 #60300] ERROR -- : can't parse 'org.jruby.RubyKernel$INVOKER$s$send19_DBG.call(org/jruby/RubyKernel$INVOKER$s$send19_DBG.gen)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.156000 #60300] ERROR -- : can't parse 'RUBY.send_to(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/contracts-0.15.0/lib/contracts/method_reference.rb:43)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.157000 #60300] ERROR -- : can't parse 'RUBY.call_with(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/contracts-0.15.0/lib/contracts/call_with.rb:79)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.157000 #60300] ERROR -- : can't parse 'RUBY.block in get_checkpoints(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/contracts-0.15.0/lib/contracts/method_handler.rb:138)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.157000 #60300] ERROR -- : can't parse 'org.jruby.RubyProc.call(org/jruby/RubyProc.java:289)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.157000 #60300] ERROR -- : can't parse 'RUBY.get_sites_with_checkpoints(/Users/pavi/dev/sdp-streams/lib/sources/bay_event_forwarder.rb:162)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.157000 #60300] ERROR -- : can't parse 'org.jruby.RubyClass.finvoke(org/jruby/RubyClass.java:522)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.158000 #60300] ERROR -- : can't parse 'org.jruby.RubyBasicObject.send19(org/jruby/RubyBasicObject.java:1680)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.158000 #60300] ERROR -- : can't parse 'org.jruby.RubyKernel.send19(org/jruby/RubyKernel.java:1998)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.158000 #60300] ERROR -- : can't parse 'org.jruby.RubyKernel$INVOKER$s$send19_DBG.call(org/jruby/RubyKernel$INVOKER$s$send19_DBG.gen)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.158000 #60300] ERROR -- : can't parse 'RUBY.send_to(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/contracts-0.15.0/lib/contracts/method_reference.rb:43)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.158000 #60300] ERROR -- : can't parse 'RUBY.call_with(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/contracts-0.15.0/lib/contracts/call_with.rb:79)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.158000 #60300] ERROR -- : can't parse 'RUBY.block in get_sites_with_checkpoints(/Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/contracts-0.15.0/lib/contracts/method_handler.rb:138)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.159000 #60300] ERROR -- : can't parse 'org.jruby.RubyProc.call(org/jruby/RubyProc.java:289)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.159000 #60300] ERROR -- : can't parse 'RUBY.start!(bin/sources/bay_event_forwarder.rb:24)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.159000 #60300] ERROR -- : can't parse 'RUBY.<main>(bin/sources/bay_event_forwarder.rb:54)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.159000 #60300] ERROR -- : can't parse 'org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:840)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.160000 #60300] ERROR -- : can't parse 'org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:844)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.160000 #60300] ERROR -- : can't parse 'org.jruby.Ruby.runNormally(org/jruby/Ruby.java:747)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.160000 #60300] ERROR -- : can't parse 'org.jruby.Ruby.runNormally(org/jruby/Ruby.java:760)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.160000 #60300] ERROR -- : can't parse 'org.jruby.Ruby.runFromMain(org/jruby/Ruby.java:573)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.160000 #60300] ERROR -- : can't parse 'org.jruby.Main.doRunFromMain(org/jruby/Main.java:417)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.160000 #60300] ERROR -- : can't parse 'org.jruby.Main.internalRun(org/jruby/Main.java:305)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.160000 #60300] ERROR -- : can't parse 'org.jruby.Main.run(org/jruby/Main.java:232)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
E, [2017-03-13T09:53:20.161000 #60300] ERROR -- : can't parse 'org.jruby.Main.main(org/jruby/Main.java:204)' (please file an issue so we can fix it: https://github.com/airbrake/airbrake-ruby/issues/new)
#<Class:0x57adfab0>: Java::OrgPostgresqlUtil::PSQLException: The connection attempt failed.
                             make_new at /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool.rb:125
                             make_new at /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:228
                            available at /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:201
                             _acquire at /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:137
                     block in acquire at /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:151
                        block in sync at /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:282
                          synchronize at org/jruby/ext/thread/Mutex.java:148
                                 sync at /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:282
                              acquire at /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:150
                                 hold at /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:106
                          synchronize at /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/database/connecting.rb:285
                       server_version at /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/adapters/shared/postgres.rb:508
                       server_version at /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/adapters/shared/postgres.rb:1793
                           select_sql at /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/dataset/sql.rb:233
                                 each at /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/dataset/actions.rb:149
                                  map at org/jruby/RubyEnumerable.java:830
                                  map at /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/sequel-4.44.0/lib/sequel/dataset/actions.rb:455
                      get_checkpoints at /Users/pavi/dev/sdp-streams/lib/sources/bay_event_forwarder.rb:147
                              send_to at /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/contracts-0.15.0/lib/contracts/method_reference.rb:43
                            call_with at /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/contracts-0.15.0/lib/contracts/call_with.rb:79
             block in get_checkpoints at /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/contracts-0.15.0/lib/contracts/method_handler.rb:138
           get_sites_with_checkpoints at /Users/pavi/dev/sdp-streams/lib/sources/bay_event_forwarder.rb:162
                              send_to at /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/contracts-0.15.0/lib/contracts/method_reference.rb:43
                            call_with at /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/contracts-0.15.0/lib/contracts/call_with.rb:79
  block in get_sites_with_checkpoints at /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/contracts-0.15.0/lib/contracts/method_handler.rb:138
                               start! at bin/sources/bay_event_forwarder.rb:24
                               <main> at bin/sources/bay_event_forwarder.rb:54

```

### PR DESCRIPTION
**Pull request by kyrylo**
Fixes #183 (Can’t parse JRuby backtrace)

The problem is that that exception appears not to be subclassed from
`Java::JavaLang::Throwable` like all other JRuby exceptions, so our
algorithm returns a pattern for an MRI exception.

The fix is naive, but it still should cover most of the cases.

### CODE REVIEW

File: lib/airbrake-ruby/backtrace.rb [hunk 1]
```diff
@@ -128,8 +128,9 @@ def self.parse(exception, logger)
     # @param [Exception] exception
     # @return [Boolean]
     def self.java_exception?(exception)
-      defined?(Java::JavaLang::Throwable) &&
-        exception.is_a?(Java::JavaLang::Throwable)
+      (defined?(Java::JavaLang::Throwable) &&
+        exception.is_a?(Java::JavaLang::Throwable)) ||
+        Patterns::JAVA =~ exception.backtrace.first
```
Comment (shifi) [inline lib/airbrake-ruby/backtrace.rb]: Nitpick: Since it's a boolean method, I would do `!!(Patterns::JAVA =~ exception.backtrace.first)`.

**Comment by shifi** [comment]
Not pending anymore 😄  🔴

File: lib/airbrake-ruby/backtrace.rb (hunk 1 above)
Comment (kyrylo) [inline lib/airbrake-ruby/backtrace.rb]: Good call. Rubocop dislikes `!!`, so I'm going to use:

`(Patterns::JAVA =~ exception.backtrace.first) != nil`
