### PR TITLE
backtrace: add support for PL/SQL exceptions

### LINKED ISSUE #98: Airbrake throws away information for incompatible backtraces
Hi,

This pull request (from what i gather) introduces a new method of parsing backtraces:

https://github.com/airbrake/airbrake-ruby/pull/4

However it errors out early when it fails to parse, throwing away the rest of the backtrace:

    raise Airbrake::Error, "can't parse '#{stackframe}'"

In my case an Oracle stored procedure call might fail, their errors are incompatible with your parser, but instead of printing the whole thing, only the last item is returned:

    Airbrake::Error (can't parse 'stmt.c:243:in oci8lib_220.so')

Example of the full "backtrace"/error message:

    OCIError: ORA-02291: integrity constraint (STORE.SN_PACE_REGISTRATIONS_FK01) violated - parent key not found
    ORA-06512: at "STORE.LI_LICENSES_PACK", line 1945
    ORA-06512: at "ACTIVATION.LI_ACT_LICENSES_PACK", line 101
    ORA-06512: at line 2
    from stmt.c:243:in oci8lib_220.bundle

Downgrading to 4.3.8 resolves the problem for me giving me:

    ORA-02291: integrity constraint (STORE.SN_PACE_REGISTRATIONS_FK01) violated - parent key not found ORA-06512: at "STORE.LI_LICENSES_PACK", line 1945 ORA-06512: at "ACTIVATION.LI_ACT_LICENSES_PACK", line 101 ORA-06512: at line 2

Note: This not only breaks airbrake integration, but hides error messages in both development mode webview and log files.

* Airbrake version: 5.4.0
* Ruby version: ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
* Framework name & version: rails (4.2.6), ruby-oci8 (2.2.2), ruby-plsql (0.6.0)

### PR DESCRIPTION
**Pull request by kyrylo**
Fixes #98
(Airbrake throws away information for incompatible backtraces)

### CODE REVIEW

File: spec/backtrace_spec.rb [hunk 1]
```diff
@@ -146,5 +146,32 @@
...
+
+      let(:ex) do
+        OCIError = AirbrakeTestError
+        OCIError.new.tap { |e| e.set_backtrace(bt) }
+      end
+
+      after { Object.__send__(:remove_const, :OCIError) }
+
+      let(:parsed_backtrace) do
+        [{ file: 'ORA-06512', line: 1945, function: 'STORE.LI_LICENSES_PACK' },
```
Comment (vmihailenco) [inline spec/backtrace_spec.rb]: `ORA-06512` does not look like a file. I think we can omit it...

Comment (vmihailenco) [inline spec/backtrace_spec.rb]: My guess is that ORA-06512 should go to error message or error type.

File: lib/airbrake-ruby/backtrace.rb [hunk 2]
```diff
@@ -38,13 +38,32 @@ module Backtrace
...
     GENERIC_STACKFRAME_REGEXP = %r{\A
+      (?:from\s)?
       (?<file>.+)              # Matches '/foo/bar/baz.ext'
       :
       (?<line>\d+)?            # Matches '43' or nothing
-      (in\s`(?<function>.+)')? # Matches "in `func'" or nothing
+      (?:
+        in\s`(?<function>.+)'    # Matches "in `func'"
+      |
+        :in\s(?<function>.+\..+) # Matches ":in func"
```
Comment (vmihailenco) [inline lib/airbrake-ruby/backtrace.rb]: It is not clear why you require dot `\.` in function name...

Comment (kyrylo) [inline lib/airbrake-ruby/backtrace.rb]: Good call, fixed, so it doesn't require it.

File: spec/backtrace_spec.rb (hunk 1 above)
Comment (kyrylo) [inline spec/backtrace_spec.rb]: I guess our best bet is to simply remove it, then.

Here's an error and type from such exception:
```
OCIError: ORA-02291: integrity constraint (STORE.SN_PACE_REGISTRATIONS_FK01) violated - parent key not found
```

OCIError is the type and the rest is the message.

**Comment by kyrylo** [comment]
I added a second commit, which removes raising. We now log the error and still parse the backtrace (see tests).

PTAL

File: spec/backtrace_spec.rb [hunk 3]
```diff
@@ -143,7 +160,38 @@
...
+         %(ORA-06512: at line 2),
+         %(from stmt.c:243:in oci8lib_220.bundle)]
+      end
+
+      let(:ex) do
+        OCIError = AirbrakeTestError
+        OCIError.new.tap { |e| e.set_backtrace(bt) }
+      end
+
+      after { Object.__send__(:remove_const, :OCIError) }
```
Comment (vmihailenco) [inline spec/backtrace_spec.rb]: `OCIError = AirbrakeTestError` and this line look strange and probably deserve a comment.

**Comment by vmihailenco** [comment]
LGTM

File: spec/backtrace_spec.rb (hunk 3 above)
Comment (kyrylo) [inline spec/backtrace_spec.rb]: Actually, I realised it can be replaced with `stub_const` from RSpec.
